# Generated by Django 4.0.4 on 2022-04-28 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='iamge',
            new_name='image',
        ),
    ]
