# Generated by Django 4.0.4 on 2022-04-28 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_iamge_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='iamge',
        ),
    ]
