# Generated by Django 4.0.3 on 2022-05-04 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='status',
            field=models.CharField(choices=[('3', '문의 등록'), ('4', '접수 완료'), ('5', '답변 완료')], default='0', max_length=5, verbose_name='상태'),
        ),
    ]
